### ISSUE TITLE
Parser misparses numeric dot-notation attribute paths

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#136]
_From [justinn...@gmail.com](https://code.google.com/u/100622539603652571415/) on February 08, 2013 11:30:14_

What steps will reproduce the problem? Source the following rule, run one decision, then print s1

sp {number-fail
   (state <s> ^superstate nil)
-->
   (<s> ^number.1 yes)
} What is the expected output? What do you see instead? Expected output (skipping architectural elements):

(S1 ^number N1)
(N1 ^1 yes)

Actual output:

(S1 ^number yes ^number 0.1) Please use labels and text to provide additional information. The problem seems to be that the ".1" in the attribute path is parsed as a float, making the action the equivalent of

(<s> ^number .1 yes)

This hypothesis is evidenced by the failure to parse the following:

sp {number-fail
   (state <s> ^superstate nil)
-->
   (<s> ^number.1.hello yes)
}

This gives the output:

Illegal value for RHS value

^
(Ignoring production number-fail)

Cursory inspection of parser.cpp (the parse_attr_value_tests function) gives no indication of why this error occurs, as the loop always checks for the dot. Which is why I'm opening an issue rather than fixing it.

_Original issue: http://code.google.com/p/soar/issues/detail?id=135_

**Comment by garfieldnate** [comment]
I think the problem is in Lexer::lex_period. When the lexer finds a period, it checks if the next thing is a number, and if it is then it generates a floating point lexeme.
The solution here would be to use context; I think if the lexer saved just one character, it could tell the difference between `^number.1.yes` and `^number .1 .yes`.

**Comment by marinier** [comment]
This is not a bug -- it is intentional behavior. Essentially, the question
is whether you want to support floats as attributes. Suppose I wanted to do
this:

(<i> ^1.2 <v>)

With the change you are suggesting, this may not be possible. With things
as they are now, you can do this, and you can still do what you wanted to
do originally (just not with dot notation).

I suppose the parser could look for a special case where a letter followed
by a period with no whitespace should always be treated as dot notation and
never as a float. That might catch most of the cases that would confuse
people.

Bob

**Comment by garfieldnate** [comment]
That's exactly what the PR does. Feel free to review it. It finds a dot after a sym constant or a variable, which I think covers it. The case of an attribute being a a float should not be not affected, although I'm not sure how to test whether `^1.2` was stored as a float or a string.

**Comment by marinier** [comment]
I think the solution you've come up with should be ok -- time will tell if
it causes problems for someone :)

To test the type of something, use the <=> test. Something like this:

sp "test
(state <s> ^{<should-be-float> <=> 1.0})
-->
(write (crlf) |It's a float|)
"

<=> is the "same type as" test. Additionally, printing the rule should show
ambiguous string symbols in pipes (e.g., if it were a string, it should
print as |1.2|), although it seems that this is not very reliable in some
of the new epmem and smem printing. (If I recall, some print function(s)
has a "rereadable" flag which determines whether pipes should be used to
disambiguate strings that look like other symbol types; e.g., floats, ints,
or ids.)
