### ISSUE TITLE
Memory leak when working in a substate

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#189]
Steps to reproduce:
1) Source the agent below.
2) Run for a while.

Expected: Memory stays flat.
Actual: Memory grows without bound.

The agent just drops into a substate, and then counts using a sub-substate (so the count is on the substate, but the operator that increments it is in the sub-substate). The number of wmes is bounded, but memory keeps growing.

This could be related to the memory growth we're seeing in jsoar.

```
sp "propose*initialize
   (state <s> ^superstate nil
             -^name)
-->
   (<s> ^operator <o> +)
   (<o> ^name initialize)
"

sp "apply*initialize
   (state <s> ^superstate.operator.name initialize)
-->
   (<s> ^name count
        ^count 0)
"

sp "count*propose*increment
   (state <s> ^name count
              ^count <c>)
-->
   (<s> ^operator <o> +)
   (<o> ^name increment
        ^value <c>)
"

sp "increment*propose*add
   (state <s> ^name increment)
-->
   (<s> ^operator <o> +)
   (<o> ^name add)
"

sp "apply*add
   (state <s> ^operator.name add
              ^superstate <ss>)
   (<ss> ^count <c>)
-->
   (<ss> ^count <c> - (+ <c> 1))
"

##!
# @brief Appends the name of the selected operator that triggered us.
# @type state-elaboration
sp {elaborate*state*name
   (state <s> ^superstate.operator.name <name>)
-->
   (<s> ^name <name>)
}
```

**Comment by bluechill** [comment]
@mazina was this ever fixed?

**Comment by mazina** [comment]
I think this growth would be expected.  When in a substate, each rule that fires will create an instantiation. So, even though it's the same rules firing over and over, replacing the same wmes, it's still creating a significant data structure with each step.  In fact, I had to add a backtracing depth cap to the explainer so that it wouldn't crash when trying to record chunks that came out of a similar agent (count-and-die).
