### ISSUE TITLE
Switch Soar to use smart pointer instead of current refcount system

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#206]
Much of the code base is tangled together due to the extensive requirement of an `agent*` argument throughout most functions. One of the reasons this is so is because of the memory allocation mechanism used; the memory manager (mem.h/cpp) maintains separate memory pools for each agent, and each allocation requires specifying which agent's memory pool to use.

It would be nice if we could switch to something like smart pointers. Mazin tells me that @bluechill worked on this last year and ran into complications, so he could explain what the ramifications/difficulties with switching to this approach are.

**Comment by marinier** [comment]
The memory pools are critical to Soar's performance. Try testing with them
disabled -- when I did this several years ago, I saw a 50% drop in
performance. Memory pools allow Soar to avoid making lots of system calls
to get memory, and it turns out that makes a huge difference.

That said, if you could tie a smart pointer mechanism to the memory pools,
so devs didn't have to track the reference counts but we still got the
performance gains, then that would be worthwhile. Note, however, that even
in jsoar we need to use reference counts for many objects (although not as
many as csoar) because some objects get trapped in lists and thus will
always have a reference -- the reference counts indicate when these objects
should be removed from these lists.

**Comment by bluechill** [comment]
So I did try to get a version running with smart pointers last year so we could see performance differences. Theoretically it shouldn't be a hit to performance because of how smart pointers work (they're reference counts internally) but what I ran into was that we use so many C style objects that in order to covert to smart pointers one basically needs to rewrite the RETE.  If you dig into the code base you'll see weird casts to void* and back with our pointers and you can't do that with smart pointers without losing their functionality.  So if someone was willing to convert Soar to not do that, smart pointers would be really nice and easy to do. But that is a big thing to try and do.  I couldn't ever make it work. I might still have a version sort of working but there was a lot of memory problems because of that.

**Comment by marinier** [comment]
So, I think you misunderstand the performance implications. The memory
pools maintain pointers to blocks of memory that have already been obtained
from the OS, so Soar can reuse these for future objects without having to
do a malloc. It's the difference between doing a system call (malloc) and
an array lookup -- a huge performance difference. And it turns out that
Soar allocates and releases lots of objects, so avoiding all of the
overhead of malloc/free makes a big difference.

That said, maybe smart pointers can be configured to use the memory pools.
It is possible to configure most STL containers to use them, for example
(Soar does this in some of the newer stuff). The configuration involves
very ugly template definitions of the container objects. The only
restriction is that the container has to always ask for objects of the same
size (vectors do not do this, and thus can't use Soar memory pools -- but
that's the only one I can think of that someone tried to use and didn't
work).

Bob

**Comment by garfieldnate** [comment]
How about the implications of not having separate pools for each agent? Would this slow down threading or anything?

**Comment by garfieldnate** [comment]
I wonder if it would be possible to just implement the memory manager to have one pool per thread. That would eliminate the need to pass the agent around everywhere for allocating.

**Comment by marinier** [comment]
I'm not sure what threads you are referring to -- there is only one thread
for all agents in csoar (jsoar supports a separate thread for each agent).
I guess the biggest issue of using a single unified set of pools (to be
clear -- there are separate pools for each object type within each agent)
is memory recovery. As it is set up now, pools can only grow, never shrink.
But destroying an agent would free all of its pools. If there was only one
set of pools for all agents, then memory could not be recovered by
destroying an agent. That said, this is an unusual edge case that I don't
recall ever coming up -- most systems are not creating and destroying lots
of agents while running. Of course, the memory pools could be redesigned to
allow for shrinkage, but I suspect this is difficult.

**Comment by garfieldnate** [comment]
Good to know. I didn't realize there were no threads, but I think they are still good to keep in mind if we update how memory works.

It looks like smart pointers can be used with memory pools just fine. You just provide your allocate/delete methods in the constructor:

    std::shared_ptr<MyClass> ptr(CreateMyObject(....), DeleteMyObject);

**Comment by marinier** [comment]
Sounds like it may be worth trying, then. I recommend looking at where
jsoar was able to eliminate reference counts and start there -- Symbols
seem like the most obvious win.

**Comment by garfieldnate** [comment]
Hmm, symbols already use reference counting, so they're a natural place to start. This cracked me up a little: `I can't remember all the places I add reference counts to symbols.  Here's a bunch I can remember though.`

**Comment by garfieldnate** [comment]
Recent changes in 9.5 have lead to some memory leaks and performance changes that must be cleaned up. Until memory management is stable and clean, this issue will be on hold.

**Comment by mazina** [comment]
I did make a memory-agnostic memory manager about 1.5 years ago, but agent is still required nearly everywhere because of other dependencies.  I'll change this to a request to switching to use smart pointers, which we really do need.

**Comment by mazina** [comment]
Moved to technical suggestion document
