### ISSUE TITLE
Adding "cli tcl on" to settings.soar doesn't work when using SoarJavaDebugger.bat

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#212]
A customer reported this issue to SoarTech (Bob M was able to reproduce):

Soar 9.4.0 on Windows, with SOAR_HOME and tcl set up correctly
1) Add "cli tcl on" to settings.soar in the bin dir
2) From the top dir (one level up from bin), run SoarJavaDebugger.bat

Expected: Tcl is loaded
Actual: Tcl is not loaded

Observations:
* Tcl loads fine if SoarJavaDebugger.jar is run directly from the bin dir
* Tcl loads fine if SoarJavaDebugger.bat is modified to change to the bin dir, like this:

    @echo off
    set SOAR_HOME=%~dp0bin
    set PATH=%SOAR_HOME%;%PATH%
    cd bin
    start javaw -jar SoarJavaDebugger.jar

Only the last two lines are changed.

The underlying issue appears to be that the working directory has to be bin at the right time. The change to SoarJavaDebugger.bat shown above could just be the solution, but I think a better solution is to take advantage of SOAR_HOME and explicitly change to that dir when loading tcl (maybe this is something the cli command can do). Of course, it would need to change back to the previous dir when finished in case something else relies on that.

No idea if other platforms or the latest in the repo are affected.

**Comment by mazina** [comment]
Hmm...something must have changed.  It seems to be in the wrong directory to load tcl even if I issue the command from the debugger, and I used to do that all the time when the plug-in was being developed.  When some time frees up, I'll look into this.

**Comment by mazina** [comment]
Doh, this was a dumb mistake.  Settings.soar doesn't work in the java debugger, because the code that loads it is in the cli program.  I'll get it moved into the kernel for 9.5.

One positive thing I noticed is that a soar java debugger with tcl loaded in 9.5 no longer crashes upon exit.

(My problem with directories and finding tcl in the previous message actually had nothing to do with this problem.  I think it was caused by a previous Rosie/BOLT install that was sourcing a file that was changing some environment variables.  I can now load it in both 9.4 release and current 9.5 development fine.)

**Comment by marinier** [comment]
I'm still seeing a crash in 9.5 when exiting the debugger with tcl loaded
(windows 7 64-bit, Java 8). Are you perhaps using an internal build that is
more recent than the release?

**Comment by mazina** [comment]
I am using the latest build, but I only tried it on the Mac side.  And I reconfirmed that on the Mac, it crashed on exit in 9.4 but not in 9.5

Unfortunately, I just tried the Windows version;  tcl loads fine in the java debugger but still crashes on exit with the same error.  For what it's worth, my Windows VM built using Java 7 while the Mac side built with Java 8.  Could be something to try.

**Comment by marinier** [comment]
I'm using Java 8, but I just have the pre-built Soar 9.5 binaries. Maybe
actually building with Java 8 would make the difference.

**Comment by mazina** [comment]
FYI, I was incorrect.  The reason it's not working is not because the loading code is in the wrong place.  The Soar kernel is indeed the one trying to load settings.soar, but it has an issue finding the file when run from the debugger.  As a workaround for now, you can probably move the settings file to whatever the current directory is at the time.

**Comment by mazina** [comment]
Resolved for both settings and tcl dll.  Unfortunately, even though Tcl dll is now found, it needs to be in the same directory as Soar.  Will add different issue report for that.
