### ISSUE TITLE
print with wildcards not working in 9.5

### ISSUE THREAD

**Issue by mazina** [SoarGroup/Soar#238]
Print with wildcards always returns no result.  For example,  p (* ^epmem *).  Reported by @amininger .  Confirmed that it doesn't work in 9.5 and does in 9.4.

**Comment by mazina** [comment]
This appears to be an issue that came out of the lexer changes made by @garfieldnate last year.  The new lexer code returns an lparen lexeme, whereas the old code would return a quoted_string, which the print command would then parse for the wild card pattern.  Nathan, could you look at this?

**Comment by garfieldnate** [comment]
I believe this is due to the change in 79bfeed1de6; I didn't quite understand how `get_lexeme_from_string` worked, and there are no tests for it. Instead of trying to parse the input string, it should be considering the input string as a single lexeme and deciding what kind of lexeme it must be. A lexeme with parentheses in it can only be a quoted string.

**Comment by mazina** [comment]
Fixed in latest commit 9cb1d79.  I re-did get_lexeme_from_string using the new Lexer's style of doing things.  Hopefully, Nathan can check it out and make sure I did it correctly.  (We really need Lexer unit tests.)
