### ISSUE TITLE
bugs in add-wme and possibly other cli commands

### ISSUE THREAD

**Issue by mazina** [SoarGroup/Soar#245]
I've confirmed a bug report on the help thread that add-wme still has problems.  For example, it no longer is able to handle strings with spaces:
```
soar % add-wme S1 ^foo |bar boo|
Error: Syntax: add-wme id [^]attribute value [+]
```
FYI, other commands may also have similar problems.  This issue is a result of changes made to the parser last year by a contributor to make it a cleaner, object-oriented Lexer class.  A few weeks ago, we discovered that several commands were broken as a result of that change.  We found the bug-- a function get_lexeme_from_string was removed that was indeed necessary -- and ported the missing code to the new framework, but it seems there are still some issues.  The other commands that also use that function to parse their arguments may also have this issue.

**Comment by garfieldnate** [comment]
I will try to look at it tonight.

**Comment by garfieldnate** [comment]
As it turns out, this bug has been here for probably several years, and it is in the CLI tokenizer, not the production lexer. I had to go back to 9.2 to see how the original logic worked for parsing commands.

Originally, variables were used to keep track of pipes, quotes and braces. The tokenizer was refactored and the logic split into several functions, and the logic for keeping track of pipe quotes was placed only inside of the function for reading sections between curly braces. If you define PRINT_CALLBACKS in tokenizer.h, you can see what's happening with `add-wme`:

    % add-wme s1 thing |a b|
    [add-wme,s1,thing,|a,b|,]

You can see that the pipes are not used as quotes here. I also see in the code, by the way, that double-quoted words inside of curly-brace sections are treated like normal characters. Is that correct? We do have doc strings, at least.

It looks like the [old code](https://soar.googlecode.com/svn/tags/Soar-Suite-9.2.0/Core/ConnectionSML/src/sml_StringOps.cpp), though, would require the nesting of quotes inside of pipes and vice-versa, which I don't think is correct, either.

Also, `add-wme s1 thing "a b"` doesn't work; the `a b` part is stripped of quotes and passed to add-wme, and then the lexer can't figure out what a string with a space but no quotes could be (that's either a bug or an intended limitation). I tried leaving the double quotes attached, but the lexer doesn't get that either (and that's definitely on purpose since bars are used for quoting normally).

I'm sending a quick PR to get piped words working, but these other issues still need some discussion.

**Comment by marinier** [comment]
I'm not sure what the answer to all these issues is, but something to keep
in mind is that Soar syntax is mostly designed with Tcl compatibility in
mind (and we use this all the time, so it's important). In Tcl, strings in
{} are treated as literals, while strings in "" can undergo variable
substitution and can execute commands (the results of which are substituted
for the command in the string). This is probably why brace sections treat
quotes as normal characters. Also, I believe Tcl compatibility is why pipes
are used as quoting characters in Soar -- it is common to wrap the entire
sp command in quotes so Tcl variables and command results can be
substituted inside, but we still need some way to quote strings internally.

**Comment by marinier** [comment]
FYI, this page gives a description of Tcl's syntax rules:

http://tmml.sourceforge.net/doc/tcl/Tcl.html

At one point, Jon Voigt actually made a concerted effort to make sure that
Soar's syntax rules adhered to the Tcl rules. But I think this led to at
least one edge case where Soar syntax was unintuitive if you weren't using
Tcl (e.g., I think braces or quote or something had to balance inside
comments, because in Tcl comments are commands). So it may deviate in that
tiny bit (and thus, there are rare cases of code working fine in Soar
without Tcl but not when the Tcl interpreter is loaded).

**Comment by garfieldnate** [comment]
Ah, I see now. The tokenizer file actually explains this fairly well, including most exceptions to TCL syntax. I think the only thing to be added to it is that end-of-line comments are handled in brace sections.

**Comment by mazina** [comment]
This fix is merged into development and passes unit tests.  Is there more that needs to be discussed or is this safe to close?

**Comment by garfieldnate** [comment]
I'm done with it. I might come back and update the documentation a little bit.

**Comment by mazina** [comment]
OK, cool.  Thanks Nathan!
