### ISSUE TITLE
Make string constants implement Unicode

### ISSUE THREAD

**Issue by PLindes** [SoarGroup/Soar#251]
In order to process data in languages other than English, it would be very helpful to have Soar handle at least string constants with Unicode.  If it did all of its parsing with Unicode that would be even better, but not as necessary.

**Comment by garfieldnate** [comment]
JXNL-Soar had plenty of Japanese strings in it, and they worked fine if they were in vertical bar quotes. That said, everyone was surprised that they worked and displayed correctly, and this would probably break somewhere (perhaps when using a multi-byte character with one byte matching that for vertical bar?) since there is no actual UTF-8 support.

**Comment by PLindes** [comment]
Well, I tried it again and found it does work to have Unicode characters
between vertical bars.  However, some of my editing tools don't handle it
well, so that was getting me very confused.  And, of course Soar doesn't
allow these characters in other places, such as rule names.  But that's not
so important as long as it works in string constants.

Thanks, Nate!
