### ISSUE TITLE
justification instantiations don't get retracted

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#26]
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 00:44:04_

Description From Bob Marinier 2007-09-14 14:57:57 (-) [reply]
Created an attachment (id=93) [details]
Code from Laird that uses up memory until crash.

1) Source the attached code
2) w 0
3) run 100000

Note two things:
- memory usage grows over time
- it takes a while to exit, but there are no unexpected leaks when it does 
so

What's happening is the code generates justifications which immediately
retract.  However, the justification instantiation is not deallocated, and 
this
leaves an extra reference count on the justification production, which then
also does not get deallocated.

Here's what happens in more detail
1) Justification is created with ref count = 1
2) Instantiation of justification is created, which increases ref count to 
2
3) Instantiation is retracted.  During this, the justification is excised,
which brings the ref count back down to 1.
4) The function possibly_deallocate_instantiation is called.  This checks 
if
inst->in_ms is 0 (it is) and inst->preferences_generated is 0 (it is not). 
Since this check fails, the instantiation is not deallocated, and thus the
reference count on the justification production never goes to zero.

What is preferences_generated?

From comments in the code:

preferences_generated:  header for a doubly-linked list of existing
        preferences that were created by this instantiation.
...
Reference counts on instantiations:
      +1 if it's in the match set
      +1 for each preference it created that's still around
   The reference count is kept implicitly using the preferences_generated
   and in_ms fields.  We deallocate an instantiation if its reference count
   goes to 0.

So where are these preferences coming from?  They appear to get generated 
by
the function make_clones_of_results.  The comments there say:

                       Make Clones of Results

   When we build the initial instantiation of the new chunk, we have
   to fill in preferences_generated with *copies* of all the result
   preferences.  These copies are clones of the results.  This routine
   makes these clones and fills in chunk_inst->preferences_generated.

This is where I'm getting stuck -- I don't understand why things are 
getting
cloned, and why they aren't going away later.

Any ideas?

_Original issue: http://code.google.com/p/soar/issues/detail?id=25_

**Comment by mazina** [comment]
I'm trying to confirm this, but I think the memory usage is expected.  This agent is both a unit test and part of TestSoarPerformance.  If I recall correctly, the memory increases because on the fourth version of counting, each count creates a new instantiation that is kept around even after the instantiation no longer matches.  They're needed to support future chunks that in that substate that may need to backtrace through them.  Every count produces a chunk that had to backtrace through one more instantiation than the last.

I had a problem with this same agent when developing the explainer code, which records a snapshot of each instantiation backtraced through.  I had to make a cap on how many instantiations it recorded to stop this agent from making the explainer cry.

I don't think there's a problem with justifications or their instantiations.  The former are deleted when they don't match regardless of refcount and the latter doesn't have refcounts.  (preferences I'm suspicious about though)
