### ISSUE TITLE
Launching Tcl from SoarJavaDebugger causes debugger to crash when exiting

### ISSUE THREAD

**Issue by mazina** [SoarGroup/Soar#263]
Aaron and I looked into this some but could not find a solution.  When launching from java, Tcl panics because it is being deleted from the wrong thread.  

For future reference, we saw that the problem gets initiated by the tcl calls that delete the slave interpreters.  At least it seemed that way at the time.

**Comment by mazina** [comment]
Resolved in recent branch by @amininger

**Comment by marinier** [comment]
Awesome! Any idea when this will show up in the nightlies?

**Comment by mazina** [comment]
No, I don't have a timeline.  Right now, the solution creates a new thread dedicated to launching and shutting down Tcl interpreters, but it uses the pthread barrier synchronization mechanism, which isn't directly available in Windows or Mac.   I've let @amininger know, and I think he's looking into either finding an equivalent or just using semaphores.

**Comment by marinier** [comment]
FYI, Soar already has a cross-platform threading interface that may be
usable or extendable for this purpose. See ConnectionSML thread_*.*

**Comment by bluechill** [comment]
General note about that interface: If it's not already using that threading interface I would use the std::thread stuff that I used for asynchronous smem. It's more portable and easier to use.  Plus Soar by default is using C++11 so it's there anyways.  I would use the conditional mutexes from STL instead of barriers (basically semaphores?)

Alex
