### ISSUE TITLE
Updating a WME value is not reflected in SML

### ISSUE THREAD

**Issue by adeschamps** [SoarGroup/Soar#275]
In the following program, I source a production that elaborates a WME from the input link to the output link. I then create an input WME, `^number 10`, then update it to `^number 20`. When I read the value off of the output-link, it still has the original value.

```c++
#include <sml_Client.h>
#include <iostream>

namespace productions {

// Elaborate WME from the input link to the output link
char const * elaborate_input =
    "sp {test*elaborate-input"
    "(state <s> ^io <io>)"
    "(<io> ^input-link.input-attribute <id>)"
    "(<io> ^output-link <ol>)"
    "-->"
    "(<ol> ^output-attribute <id>)"
    "}";

} // namespace productions

int main()
{
    auto* kernel = sml::Kernel::CreateKernelInCurrentThread();
    auto* agent = kernel->CreateAgent("test-agent");
    kernel->ExecuteCommandLine(
        productions::elaborate_input, agent->GetAgentName());

    auto* il = agent->GetInputLink();
    auto* input_id = il->CreateIdWME("input-attribute");
    auto* input_number = input_id->CreateFloatWME("number", 10);

    agent->RunSelf(1);
    input_number->Update(20);
    agent->RunSelf(1);

    // With the following line uncommented,
    // we will read the correct value.
    // agent->SynchronizeOutputLink();

    auto* ol = agent->GetOutputLink();
    auto* output_id = ol->FindByAttribute("output-attribute", 0)->ConvertToIdentifier();

    auto* output_number = output_id->FindByAttribute("number", 0)->ConvertToFloatElement();
    // Will print `^number 10`
    std::cout << "^number " << output_number->GetValue() << "\n";
}
```

If I call `SynchronizeOutputLink()`, then I get the behaviour I expect. But the docs for that function say that calling it probably shouldn't be necessary, which makes me wonder if something else is wrong.

**Comment by amininger** [comment]
The main thing is that from soar's perspective, nothing changed on the output link. That is, nothing was added or removed. When the 'number' changed from 10 to 20, this was done by SML, not a rule, so the thing that monitors changes to the output link never noticed the change. Synchronize output link makes sure this happens. I would recommend using the following rule instead:
`sp {test*elaborate-input
   (state <s> ^io <io>)
   (<io> ^input-link.input-attribute <ia>
         ^output-link <ol>)
   (<ia> ^number <n>)
-->
   (<ol> ^output-attribute <oa>)
   (<oa> ^number <n>)
}`
Note that because of the way soar runs when you say agent->RunSelf, you will have to have it run 2 dc's. This is because when you change the number to 20 and call agent->RunSelf(1), it covers the input phase, but doesn't cover the subsequent output phase. So change it to agent->RunSelf(2) and it should work.
