### ISSUE TITLE
production firing-counts options --task, --templates, and --fired don't work

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#298]
In the 9.6.0 release, the help for production firing-counts indicates that the options `--task`, `--templates`, and `--fired` should work, but they don't appear to. E.g.,

```
production firing-counts --fired
No such option: fired
```

**Comment by mazina** [comment]
- production firing-count --task shouldn't work.  I think --task is only a production excise option.
- production firing-count --template is the command, not --templates.  That's a typo in the help file.  (Also confusing b/c another command uses --templates.)
- production firing-count -f will work but --fired won't.  **This is definitely a bug.**  

By the way, I know the large consolidated help results can be confusing, especially since sub-commands can have different parameters and even parameter styles.  The plan is to one day have hierarchical help that will list the help for each subcommand individually.  And hopefully one day we can make the various command options more consistent as well.

**Comment by marinier** [comment]
The help definitely shows task as an option for production firing-counts
(and also for production excise). Presumably just a typo.

**Comment by garfieldnate** [comment]
@marinier Shall I change the --template to --templates for consistency?

**Comment by garfieldnate** [comment]
@marinier Actually, maybe the other way would be better. The help docs are mixed between `templates` and `template`, but all of the implementations. So I think the better solution is to change the docs to `--template` everywhere.

These are the commands that use `--template`:

* production firing-counts
* production excise
* production memory-usage
* trace
* print

**Comment by garfieldnate** [comment]
But then it's confusing that `--template` is the only option that uses singular T_T There's also `--justifications` and `--chunks`. Maybe better to go with `--templates` after all.

**Comment by garfieldnate** [comment]
And now that I've looked at the code I realize we just take the longest match for an option, so if we accept `--templates` we'll also accept `--template`. Problem solved :)
