### ISSUE TITLE
Probable typo in documentation for production optimize-attribute

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#300]
In the output of the `help production` command, in the section on `production optimize-attribute`, it says of the numeric parameter:

```
n      Integer greater than 1, estimate of degree of simultaneous values for
       attribute.
```

In fact is accepts any integer greater than 0 (that is, it accepts 1). This is probably a typo in the help, but maybe the command actually shouldn't accept 1?

**Comment by garfieldnate** [comment]
I've opted to update the documents instead of changing the behavior, as I'm not sure how clients are using this. Setting n to 0 results in using the default value of 10. Setting n to 1 allows a client to undo a previous declaration of multiple values, and does no harm if a client calculates the value and comes up with 1 as a base case for some reason (seems highly unlikely). If you would rather the command be stricter, we can revisit this.

**Comment by scijones** [comment]
1 is acceptable. It's "weird", but the "undo a previous declaration of multiple values" argument has me swayed.
