### ISSUE TITLE
help erroneously reports that some commands don't exist

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#301]
`help ls`, `help cd`, `help popd`, and `help pushd` all produce output like this:

```
No such command 'ls'.
```

But in fact these commands do work. Perhaps because these are all file system related that they are handled by a different code path not covered by help? Anyway, it would be worth at least preventing help from claiming these don't exist, as that could lead users astray.

**Comment by mazina** [comment]
Those commands are in the help system, thought it might not be as obvious as before.  You can  find them under ```help file-system```.  

It was an intentional choice, but I do think there's something we can do to improve it.   Perhaps, if the help menu showed some individual file commands, you would have noticed there was an entry that had what you were looking for, for example:  
```
alias
chunk
debug
decide
echo
epmem
explain
file-system **(cd, ls, pushd, etc.)**
gp
help
load
output
preferences
print
production
rl
run
save
smem
soar
sp
stats
svs
trace
visualize
wm
```
Also, there's some backwards-compatibility help code that maps old commands to new commands.  While the file system commands are still current commands, I could add them to the to that mapping list so that stuff like 'help ls' will return the result of 'help file system'.

**Comment by mazina** [comment]
We should also change the error to say that no help file exist rather than no such command.
