### ISSUE TITLE
make-constant-symbol doesn't seem to work without an argument

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#316]
`make-constant-symbol` takes an optional argument (defaults to `constant`) and generates a unique string using an autoincrementing value.

In the 9.6.0 release on Windows 10, running in the SoarJavaDebugger with Java 8, if I load this rule and `step`:

```
sp "test
(state <s> ^superstate nil)
-->
(write (crlf) (make-constant-symbol foo))"
```
I get the expected `foo1`, and then if I `init` and `step` again I get `foo2`, etc.

However, if I remove the `foo` argument, like this:
```
sp "test
(state <s> ^superstate nil)
-->
(write (crlf) (make-constant-symbol))"
```
and then `step`, `init`, `step`, `init`, etc., it just prints `constant` out repeatedly, with no number. No number is ok the first time, but the second time it should be unique, and and thus be `constant1` (this is actually jsoar's behavior, which was originally ported from csoar long ago).

**Comment by mazina** [comment]
I can see why it's happening.  make-constant-symbol only creates a symbol with an incremented number if the base symbol, in this case "constant",  already exists.  Unfortunately, when you init, the symbol gets deallocated because it's not actually used in the original rule and was just a side-effect of a RHS action.   In fact, if that rule that performed make-constant-symbol stopped matching, it would probably reset the counter in the middle of the run.

If you need a temporary workaround for your branch, try adding the string "constant" to a dummy rule.  I haven't tested it, but I think such a rule should be enough to keep the symbol in memory, even if it never fires, which should allow the counter to work properly.

**Comment by marinier** [comment]
That makes sense. It actually seems to deallocate the symbol even earlier. Consider this rule:

```
sp "test
(state <s> ^superstate nil)
-->
(write (crlf) (make-constant-symbol))
(write (crlf) (make-constant-symbol))"
```
This prints `constant` twice, even though there is no init. However, if I change the rule like this (note the new condition):

```
sp "test
(state <s> ^superstate nil -^constant)
-->
(write (crlf) (make-constant-symbol))
(write (crlf) (make-constant-symbol))"
```
Then it prints `constant1` and `constant2`.

I suspect the reason jsoar behaves differently is because the symbol doesn't necessarily get cleaned up right away. The current symbols are held in a weak map, which means the garbage collector can clean them up whenever it feels like it, which may be a while, and hence the symbols still exist in the tests I described.

Anyway, it's not causing any problems for us. It was more of an unexpected behavior that I ran across, but it doesn't seem to be a bug, so I'll just close it.

**Comment by mazina** [comment]
I found an easy way to fix it.  (I added "constant" to our list of predefined symbols that never get deallocated.)  It has been pushed to development.

Behavior is slightly changed.  First call to make-constant-symbol will return "constant1" rather than "constant".
