### ISSUE TITLE
How-to doc on ROS node running a Soar kernel

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#372]
Via user @moschmdt

A fairly popular use of Soar is to run a kernel in a ROS node, but there's no documentation on how to do this. It would be great to have a quick-start and basic tutorial for people starting new ROS projects.

**Comment by JayJayyOlimb** [comment]
Hi there, are there any news on this? :) Especially something related to ROS2 would be helpful.

**Comment by moschmdt** [comment]
I am currently writing a ROS2 package that creates wrappers for Soar and also does some background work, e.g. running the kernel in a separate thread so ROS and Soar don't block each other. I think it will be ready soon (1-2 weeks)

**Comment by JayJayyOlimb** [comment]
Nice, thanks for the update.

**Comment by moschmdt** [comment]
I made the project public now as [soar_ros](https://github.com/THA-Embedded-Systems-Lab/soar_ros) and there is a [website with documentation](https://tha-embedded-systems-lab.github.io/soar_ros/) (to be extended).

@garfieldnate Could you please close this? I can't do it since I am not the creator of the issue.

**Comment by garfieldnate** [comment]
Okay, thank you! When you're ready for a more "official" release, it would be helpful to have an announcement on the Soar mailing list. I can add a link to the Soar website when you're ready, as well.
