### ISSUE TITLE
can't always right-click to print WME's

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#417]
Sometimes printed WME names can't be right-clicked to print. For example, I had this output in the ITL agent:

    p i3
    (I3 ^perform-action P8596)

Right-clicking `P8596` opens the general right-click menu instead of the special one for printing WME's. I'm wondering if maybe there's a regex that doesn't expect WME's to be this long or something.

**Comment by PLatCIC** [comment]
I've seen this kind of problem a lot, and I don't think it has anything to do with regexes. Instead, what I see it that the point where you do the right click doesn't line up well with what you want to see. For instance, often I have had to right click two text lines below the identifier I want to print in order to get the menu for that identifier to pop up. There seems to be an offset between the point I think I'm clicking on and the point in the window where the debugger recognizes the click. I've noticed that this offset varies with the font size being used and the vertical position in the window. The offset is much less near the top of the window than near the bottom.
I suggest looking at how the cursor position given by a right click correlates with a position in the text the debugger is displaying.
