### ISSUE TITLE
Incorrect run control via Agent.RunSelf during optimized run

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#92]
_From [nate.der...@gmail.com](https://code.google.com/u/105203827464787627414/) on June 18, 2011 13:44:07_

What steps will reproduce the problem? 1. Create an optimized kernel
2. RunSelf(7, smlRunStepSize.sml_PHASE) vs. ExecuteCommandLine("run --self -p 7")
3. GetDecisionCycleCounter, GetCurrentPhase What is the expected output? What do you see instead? Expected: identical output
Actual...

RunSelf=2, sml_INPUT_PHASE
CLI=1, sml_DECISION_PHASE

For reference, non-optimized...

RunSelf=1, sml_DECISION_PHASE
CLI=1, sml_DECISION_PHASE

Optimized run control uses sml_DirectRun (sml_KernelSML.cpp) instead of CLI and something is different in the execution.

The above output was generated using Java SML on r12742 .

_Original issue: http://code.google.com/p/soar/issues/detail?id=91_

**Comment by mazina** [comment]
Fixed in latest commit.  Agent::RunSelf used a hard-coded sml_DECISION for interleave parameter when in optimized mode.  When in non-optimized mode, it would send it to CLI which would replace default interleave parameter (also decision) with the stepsize passed in.

Agent::RunSelf in optimized mode now just sends the step size for both step size and interleave parameters which should be equivalent to what the CLI does.  Confirmed all four cases now end at the same dc and phase.
